### ISSUE TITLE
괄호를 두번 쓰는 부분

### ISSUE THREAD

**Issue by bbb1293** [bivoje/challenges#6]
three(append_pip)("counting..") #=> "counting.. pip pip pip"

이 부분과 바로 밑의

_three(append_pip)("counting..") #=> "counting.. pip pip pip"

가 무슨 차이가 있는지 모르겠다. 괄호를 두번 쓰는 것을 한 번 쓰는것으로 바꾸어놓고 도우미 함수를 이용해서 왜 또 괄호를 두번쓰는가;;

**Comment by bivoje** [comment]
고거는 _three를 three랑 동일하게 사용 가능함을 보여주려고 쓴건데;; 일단 밑에 설명 추가함
